---
- name: create new aws instance
  hosts: localhost
  gather_facts: false
  vars:
    group_name: "{{ group_name }}"
  roles:
    - precheck
    - aws
  vars_files:
    - vars/aws.yml
    - vars/key.yml

- name: configure on new instance
  hosts: "{{ host_name }}"
  gather_facts: true
  become: true
  roles:
    - mount_volume
    - docker
    - nginx
    - html_count
    - log
  vars_files:
    - vars/aws.yml
